# cargo

# [[file:~/Workspace/Programming/gosh-rs/models/models.note::*cargo][cargo:1]]
[package]
name = "gosh-model"
version = "0.0.8"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
serde = "1.0"
envy = "0.4"
serde_json = "1.0"
dotenv = "0.13"
duct = "0.13"
tempfile = "3.0"
gosh-core = { version = "0.0.1" }

[dev-dependencies]
approx = "0.3"

[features]
adhoc = []
# cargo:1 ends here
