# cargo

# [[file:~/Workspace/Programming/gosh-rs/models/models.note::*cargo][cargo:1]]
[package]
name = "gosh-models"
version = "0.0.7"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
serde = "1.0"
envy = "0.4"
serde_json = "1.0"
dotenv = "0.13"
duct = "0.13"
tempfile = "3.0"
runners = {path = "../runners"}
vecfx = {git = "https://github.com/gchemol/vecfx.git", features=["nalgebra"]}
guts = { git = "https://github.com/ybyygu/guts.git", branch = "dev" }
gchemol = {git = "https://github.com/ybyygu/gchemol.git"}

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
