# cargo

# [[file:~/Workspace/Programming/gosh-rs/models/models.note::*cargo][cargo:1]]
[package]
name = "gosh-models"
version = "0.0.3"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
quicli = "0.4"
serde = "1.0"
envy = "0.4"
serde_json = "1.0"
dotenv = "0.13"
duct = "0.12"
tempfile = "3.0"
vecfx = {git = "https://github.com/gchemol/vecfx.git", tag="v0.0.3", features=["nalgebra"]}
#gchemol = {git = "https://github.com/ybyygu/gchemol.git", tag="v0.0.29"}
gchemol = {path = "/home/ybyygu/Workspace/Programming/gchemol-rs/gchemol/gchemol"}

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
